<%@ Page Language="C#" AutoEventWireup="true" CodeFile="foodtest.aspx.cs" Inherits="foodtest" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<link href="Styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <title></title>
    </head>
<body>
        <form id="form1" runat="server" role="form" class="container">
    <div align="center" class="page-header">
    <p class="h1">Guest Food Billing</p>
    </div>
    <div class="container">
        
        <div class="container">
            <div class="col-md-4">
            <div class="text-center text-primary h3 ">
            Date:
            <asp:Label ID="label" runat="server"></asp:Label>
        </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <p>Enter Room No. </p>
                            <asp:DropDownList  ID="roomlist"  CssClass=" form-control"  runat="server">
                            </asp:DropDownList>
                             <div style="margin: 10px">
                            <asp:Button ID="check" runat="server"  onclick="check_Click" Text="Check" />
                            </div>

                            <asp:DropDownList    ID="namelist"  CssClass=" form-control" runat="server" Visible="False">
                            </asp:DropDownList>
                       
                       
                    <li class="list-group-item">
                        <p>Select Item</p>
                        <asp:DropDownList ID="foodlist" runat="server" CssClass=" form-control">
                        </asp:DropDownList>
                    </li>
                    <li class="list-group-item">
                        <p>Quantity</p>
                        <asp:TextBox ID="qty" runat="server" TextMode="Number" CssClass="form-control">1</asp:TextBox>
                      </li>
                     </ul>
                 <asp:Button ID="additem" runat="server" Text="Add" OnClick="add_Click" CssClass="btn-success btn-lg" Visible="false" />
                 <asp:Button ID="edit" runat="server" Text="Check/Edit for Today" 
                    OnClick="edit_Click" CssClass="btn-info btn-lg" Visible="false"/>
                 <div class="h3">
            Total Amount for day =
            <asp:Label ID="sumtotal" runat="server" Text="0"></asp:Label>
        </div>
        <div>
        <a href="GrandUnifiedLoggedIn.aspx" ><span class="btn-warning btn-lg">Back</span></a>
        </div>
            </div>
            <div align="center" class="col-lg-8">
               
                <asp:GridView ID="foodview" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="OnRowDeleting"
                    DataKeyNames="refno,item" CellPadding="4" Height="100%" Width="100%" 
                    BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" 
                    BorderWidth="1px" ForeColor="Black" GridLines="Vertical">
                    <AlternatingRowStyle BackColor="White" />
                    <FooterStyle BackColor="#CCCC99" />
                    <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                    <PagerStyle ForeColor="Black" HorizontalAlign="Right" BackColor="#F7F7DE" />
                    <RowStyle BackColor="#F7F7DE" />
                    <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#FBFBF2" />
                    <SortedAscendingHeaderStyle BackColor="#848384" />
                    <SortedDescendingCellStyle BackColor="#EAEAD3" />
                    <SortedDescendingHeaderStyle BackColor="#575357" />
                </asp:GridView>
            </div>
        </div>
        
    </div>
    </form>

    <script src="Scripts/jquery-1.11.3.min.js" type="text/javascript"></script>
    <script src="bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <script src="Scripts/bootstrap-select.min.js" type="text/javascript"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            $(".selectpicker").selectpicker();

        });

</script>
</body>
</html>
