<?xml version="1.0" encoding="utf-8"?><Database Name="MasterData" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.118.51.10;Initial Catalog=MasterData;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MasterDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmployeeMaster" Member="EmployeeMasters">
    <Type Name="EmployeeMaster">
      <Column Name="MANDT" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="EMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CERTIFICATIONDSC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MARRITALSTADESC" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PREREPORTTOFNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PREREPORTTOEMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TSHOMECONTRYDESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PREREPRTTOEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ACTION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ACTIONDESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="STATUSDESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="REASONACTION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="REASONACTIONDESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EMPLOYMENTSTATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EMPMNTSTATUSDESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="COMPANY" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="COMPANYDESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="COSTCENTER" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="COSTCENTERDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="COMPANYLOCATION" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="COMPANYJOINDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TRAININGDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PROBATIONDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CONTRACTDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CONFIRMATIONDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LOCATION" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="LOCATIONDESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EMPGROUP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="GROUPDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DESIGNATION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DESIGNATIONDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GRADE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BUSAREA" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BUSAREADESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DEPARTMENT" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="DEPARTMENTDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BRANCHID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="BRANCHIDDESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAYROLL" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PAYROLLDESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ROLEDESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PLANS" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HODPLANS" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="HODEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HODFULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HODEMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HODDESG" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="HODDESGDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HODGRADE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="EMPREPORTTOPLANS" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="REPORTTOEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="REPORTTOFULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="REPORTTOEMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REPORTTODESG" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="REPORTTODESGDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="REPORTTOGRADE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="LNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="REGION" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BIRTHPLACE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BIRTHCOUNTRY" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BIRTHCOUNTRYDESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="REGIONDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MOBILENO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LANDLINE" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EDUCOMPLETION" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSTITUTE" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="CERTIFICATION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="EDUCATION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="EDUCATIONDESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EDUCLASS" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PERCENTAGE" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="EDUGRADE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PANNO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PASSPORT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PASSPORTEXPDATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PASSPORTISSUING" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="PASSPORTCOUNTRY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="STREET" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DISTRICT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="POSTALCODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HOMECOUNTRY" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="HOMETELEPHONE" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="STREETLINE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="HOMEREGION" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="HOMEREGIONDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HOMECOUNTRYDESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ENTRYINTOGROUP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CORPORATION" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CORPORATIONDESC" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MOTHER_FNAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="MOTHER_LNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MOTHERDOB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FATHER_FNAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="FATHER_LNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FATHERDOB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="WIFE_FNAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="WIFE_LNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="WIFEDOB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LASTPROMOTION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LASTCOMPANY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LASTCOMPANYJOIN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LASTCOMPANYLEAVE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PREEMPNUMBER" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="LEAVEENTITLE" Type="System.Decimal" DbType="Decimal(10,5)" CanBeNull="true" />
      <Column Name="LEAVEREST" Type="System.Decimal" DbType="Decimal(10,5)" CanBeNull="true" />
      <Column Name="LEAVEDEDUCT" Type="System.Decimal" DbType="Decimal(10,5)" CanBeNull="true" />
      <Column Name="BLOODGROUPID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BLOODGROUPDESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="MARRITALSTATUSID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NOOFCHILD" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="NATIONALITY" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATIONALITYDESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="GENDERDESC" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ANNIVERSARYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RELIGION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RELIGIONDESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="RETIREMENT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BANKACCOUNT" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="BANKNAME" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PREHODEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PREHODFULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PREHODEMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PREREPORTTOEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PREREPORTTOPLANS" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="DEPTLASTCHANGE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PREREPORTTOCOMP" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="PREREPORTTOLOC" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="PREREPORTTODEPT" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="PREREPORTTOROLE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TSSTREET" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="TSCITY" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="TSDISTRICT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="TSPOSTALCODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TSHOMECOUNTRY" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="TSHOMETELEPHONE" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="TSSTREETLINE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="TSHOMEREGION" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="TSHOMEREGIONDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JOINEDAS" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="JOINEDASDESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LEAVECOP" Type="System.String" DbType="VarChar(17)" CanBeNull="true" />
      <Column Name="LEAVECOT" Type="System.String" DbType="VarChar(17)" CanBeNull="true" />
      <Column Name="EMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="HODEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="REPORTTOEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PREHODEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="STAR" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="REPORTTOPLANS" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="REVEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="REVFULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="REVEMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REVDESG" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="REVDESGDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="REVGRADE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="REVEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="MATEMPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MATFULLNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="MATEMAILID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MATDESG" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="MATDESGDESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MATGRADE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="MATEMPID6" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="MATPLANS" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="HAVEMATRIXMGR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REVPLANS" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="ESSAPPID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ESSAPPNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ESSAPPINTA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_AGE" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="EMP_EXP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_EXITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMP_BANKIFSC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_TSBLOCK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_TSFLATNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_ACTIVE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>