#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MasterData")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MasterDataConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<EmployeeMaster> EmployeeMasters
	{
		get
		{
			return this.GetTable<EmployeeMaster>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeMaster")]
public partial class EmployeeMaster
{
	
	private string _MANDT;
	
	private string _EMPID;
	
	private string _CERTIFICATIONDSC;
	
	private string _MARRITALSTADESC;
	
	private string _PREREPORTTOFNAME;
	
	private string _PREREPORTTOEMAIL;
	
	private string _TSHOMECONTRYDESC;
	
	private string _PREREPRTTOEMPID6;
	
	private string _ACTION;
	
	private string _ACTIONDESC;
	
	private string _STATUS;
	
	private string _STATUSDESC;
	
	private string _REASONACTION;
	
	private string _REASONACTIONDESC;
	
	private string _EMPLOYMENTSTATUS;
	
	private string _EMPMNTSTATUSDESC;
	
	private string _COMPANY;
	
	private string _COMPANYDESC;
	
	private string _COSTCENTER;
	
	private string _COSTCENTERDESC;
	
	private string _COMPANYLOCATION;
	
	private string _COMPANYJOINDATE;
	
	private string _TRAININGDATE;
	
	private string _PROBATIONDATE;
	
	private string _CONTRACTDATE;
	
	private string _CONFIRMATIONDATE;
	
	private string _LOCATION;
	
	private string _LOCATIONDESC;
	
	private string _EMPGROUP;
	
	private string _GROUPDESC;
	
	private string _DESIGNATION;
	
	private string _DESIGNATIONDESC;
	
	private string _GRADE;
	
	private string _BUSAREA;
	
	private string _BUSAREADESC;
	
	private string _DEPARTMENT;
	
	private string _DEPARTMENTDESC;
	
	private string _BRANCHID;
	
	private string _BRANCHIDDESC;
	
	private string _PAYROLL;
	
	private string _PAYROLLDESC;
	
	private string _ROLE;
	
	private string _ROLEDESC;
	
	private string _PLANS;
	
	private string _HODPLANS;
	
	private string _HODEMPID;
	
	private string _HODFULLNAME;
	
	private string _HODEMAILID;
	
	private string _HODDESG;
	
	private string _HODDESGDESC;
	
	private string _HODGRADE;
	
	private string _EMPREPORTTOPLANS;
	
	private string _REPORTTOEMPID;
	
	private string _REPORTTOFULLNAME;
	
	private string _REPORTTOEMAILID;
	
	private string _REPORTTODESG;
	
	private string _REPORTTODESGDESC;
	
	private string _REPORTTOGRADE;
	
	private string _FULLNAME;
	
	private string _FNAME;
	
	private string _MNAME;
	
	private string _LNAME;
	
	private string _DOB;
	
	private string _REGION;
	
	private string _BIRTHPLACE;
	
	private string _BIRTHCOUNTRY;
	
	private string _BIRTHCOUNTRYDESC;
	
	private string _REGIONDESC;
	
	private string _MOBILENO;
	
	private string _LANDLINE;
	
	private string _EMAILID;
	
	private string _EDUCOMPLETION;
	
	private string _INSTITUTE;
	
	private string _CERTIFICATION;
	
	private string _EDUCATION;
	
	private string _EDUCATIONDESC;
	
	private string _EDUCLASS;
	
	private string _PERCENTAGE;
	
	private string _EDUGRADE;
	
	private string _PANNO;
	
	private string _PASSPORT;
	
	private string _PASSPORTEXPDATE;
	
	private string _PASSPORTISSUING;
	
	private string _PASSPORTCOUNTRY;
	
	private string _STREET;
	
	private string _CITY;
	
	private string _DISTRICT;
	
	private string _POSTALCODE;
	
	private string _HOMECOUNTRY;
	
	private string _HOMETELEPHONE;
	
	private string _STREETLINE;
	
	private string _HOMEREGION;
	
	private string _HOMEREGIONDESC;
	
	private string _HOMECOUNTRYDESC;
	
	private System.Nullable<System.DateTime> _ENTRYINTOGROUP;
	
	private string _CORPORATION;
	
	private string _CORPORATIONDESC;
	
	private string _MOTHER_FNAME;
	
	private string _MOTHER_LNAME;
	
	private string _MOTHERDOB;
	
	private string _FATHER_FNAME;
	
	private string _FATHER_LNAME;
	
	private string _FATHERDOB;
	
	private string _WIFE_FNAME;
	
	private string _WIFE_LNAME;
	
	private string _WIFEDOB;
	
	private System.Nullable<System.DateTime> _LASTPROMOTION;
	
	private string _LASTCOMPANY;
	
	private System.Nullable<System.DateTime> _LASTCOMPANYJOIN;
	
	private System.Nullable<System.DateTime> _LASTCOMPANYLEAVE;
	
	private string _PREEMPNUMBER;
	
	private System.Nullable<decimal> _LEAVEENTITLE;
	
	private System.Nullable<decimal> _LEAVEREST;
	
	private System.Nullable<decimal> _LEAVEDEDUCT;
	
	private string _BLOODGROUPID;
	
	private string _BLOODGROUPDESC;
	
	private string _MARRITALSTATUSID;
	
	private System.Nullable<decimal> _NOOFCHILD;
	
	private string _NATIONALITY;
	
	private string _NATIONALITYDESC;
	
	private string _GENDER;
	
	private string _GENDERDESC;
	
	private System.Nullable<System.DateTime> _ANNIVERSARYDATE;
	
	private string _RELIGION;
	
	private string _RELIGIONDESC;
	
	private System.Nullable<System.DateTime> _RETIREMENT;
	
	private string _BANKACCOUNT;
	
	private string _BANKNAME;
	
	private string _PREHODEMPID;
	
	private string _PREHODFULLNAME;
	
	private string _PREHODEMAILID;
	
	private string _PREREPORTTOEMPID;
	
	private string _PREREPORTTOPLANS;
	
	private string _DEPTLASTCHANGE;
	
	private string _PREREPORTTOCOMP;
	
	private string _PREREPORTTOLOC;
	
	private string _PREREPORTTODEPT;
	
	private string _PREREPORTTOROLE;
	
	private string _TSSTREET;
	
	private string _TSCITY;
	
	private string _TSDISTRICT;
	
	private string _TSPOSTALCODE;
	
	private string _TSHOMECOUNTRY;
	
	private string _TSHOMETELEPHONE;
	
	private string _TSSTREETLINE;
	
	private string _TSHOMEREGION;
	
	private string _TSHOMEREGIONDESC;
	
	private string _JOINEDAS;
	
	private string _JOINEDASDESC;
	
	private string _LEAVECOP;
	
	private string _LEAVECOT;
	
	private string _EMPID6;
	
	private string _HODEMPID6;
	
	private string _REPORTTOEMPID6;
	
	private string _PREHODEMPID6;
	
	private string _STAR;
	
	private string _REPORTTOPLANS;
	
	private string _REVEMPID;
	
	private string _REVFULLNAME;
	
	private string _REVEMAILID;
	
	private string _REVDESG;
	
	private string _REVDESGDESC;
	
	private string _REVGRADE;
	
	private string _REVEMPID6;
	
	private string _MATEMPID;
	
	private string _MATFULLNAME;
	
	private string _MATEMAILID;
	
	private string _MATDESG;
	
	private string _MATDESGDESC;
	
	private string _MATGRADE;
	
	private string _MATEMPID6;
	
	private string _MATPLANS;
	
	private string _HAVEMATRIXMGR;
	
	private string _REVPLANS;
	
	private string _ESSAPPID;
	
	private string _ESSAPPNAME;
	
	private string _ESSAPPINTA;
	
	private string _EMP_AGE;
	
	private string _EMP_EXP;
	
	private System.Nullable<System.DateTime> _EMP_EXITDATE;
	
	private string _EMP_BANKIFSC;
	
	private string _EMP_TSBLOCK;
	
	private string _EMP_TSFLATNO;
	
	private string _EMP_ACTIVE;
	
	public EmployeeMaster()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANDT", DbType="VarChar(3)")]
	public string MANDT
	{
		get
		{
			return this._MANDT;
		}
		set
		{
			if ((this._MANDT != value))
			{
				this._MANDT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPID", DbType="VarChar(8)")]
	public string EMPID
	{
		get
		{
			return this._EMPID;
		}
		set
		{
			if ((this._EMPID != value))
			{
				this._EMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CERTIFICATIONDSC", DbType="VarChar(40)")]
	public string CERTIFICATIONDSC
	{
		get
		{
			return this._CERTIFICATIONDSC;
		}
		set
		{
			if ((this._CERTIFICATIONDSC != value))
			{
				this._CERTIFICATIONDSC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARRITALSTADESC", DbType="VarChar(6)")]
	public string MARRITALSTADESC
	{
		get
		{
			return this._MARRITALSTADESC;
		}
		set
		{
			if ((this._MARRITALSTADESC != value))
			{
				this._MARRITALSTADESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOFNAME", DbType="VarChar(40)")]
	public string PREREPORTTOFNAME
	{
		get
		{
			return this._PREREPORTTOFNAME;
		}
		set
		{
			if ((this._PREREPORTTOFNAME != value))
			{
				this._PREREPORTTOFNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOEMAIL", DbType="VarChar(100)")]
	public string PREREPORTTOEMAIL
	{
		get
		{
			return this._PREREPORTTOEMAIL;
		}
		set
		{
			if ((this._PREREPORTTOEMAIL != value))
			{
				this._PREREPORTTOEMAIL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSHOMECONTRYDESC", DbType="VarChar(15)")]
	public string TSHOMECONTRYDESC
	{
		get
		{
			return this._TSHOMECONTRYDESC;
		}
		set
		{
			if ((this._TSHOMECONTRYDESC != value))
			{
				this._TSHOMECONTRYDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPRTTOEMPID6", DbType="VarChar(6)")]
	public string PREREPRTTOEMPID6
	{
		get
		{
			return this._PREREPRTTOEMPID6;
		}
		set
		{
			if ((this._PREREPRTTOEMPID6 != value))
			{
				this._PREREPRTTOEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTION", DbType="VarChar(2)")]
	public string ACTION
	{
		get
		{
			return this._ACTION;
		}
		set
		{
			if ((this._ACTION != value))
			{
				this._ACTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIONDESC", DbType="VarChar(30)")]
	public string ACTIONDESC
	{
		get
		{
			return this._ACTIONDESC;
		}
		set
		{
			if ((this._ACTIONDESC != value))
			{
				this._ACTIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(1)")]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this._STATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSDESC", DbType="VarChar(40)")]
	public string STATUSDESC
	{
		get
		{
			return this._STATUSDESC;
		}
		set
		{
			if ((this._STATUSDESC != value))
			{
				this._STATUSDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REASONACTION", DbType="VarChar(2)")]
	public string REASONACTION
	{
		get
		{
			return this._REASONACTION;
		}
		set
		{
			if ((this._REASONACTION != value))
			{
				this._REASONACTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REASONACTIONDESC", DbType="VarChar(30)")]
	public string REASONACTIONDESC
	{
		get
		{
			return this._REASONACTIONDESC;
		}
		set
		{
			if ((this._REASONACTIONDESC != value))
			{
				this._REASONACTIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYMENTSTATUS", DbType="VarChar(1)")]
	public string EMPLOYMENTSTATUS
	{
		get
		{
			return this._EMPLOYMENTSTATUS;
		}
		set
		{
			if ((this._EMPLOYMENTSTATUS != value))
			{
				this._EMPLOYMENTSTATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPMNTSTATUSDESC", DbType="VarChar(40)")]
	public string EMPMNTSTATUSDESC
	{
		get
		{
			return this._EMPMNTSTATUSDESC;
		}
		set
		{
			if ((this._EMPMNTSTATUSDESC != value))
			{
				this._EMPMNTSTATUSDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(4)")]
	public string COMPANY
	{
		get
		{
			return this._COMPANY;
		}
		set
		{
			if ((this._COMPANY != value))
			{
				this._COMPANY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANYDESC", DbType="VarChar(25)")]
	public string COMPANYDESC
	{
		get
		{
			return this._COMPANYDESC;
		}
		set
		{
			if ((this._COMPANYDESC != value))
			{
				this._COMPANYDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTCENTER", DbType="VarChar(10)")]
	public string COSTCENTER
	{
		get
		{
			return this._COSTCENTER;
		}
		set
		{
			if ((this._COSTCENTER != value))
			{
				this._COSTCENTER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTCENTERDESC", DbType="VarChar(20)")]
	public string COSTCENTERDESC
	{
		get
		{
			return this._COSTCENTERDESC;
		}
		set
		{
			if ((this._COSTCENTERDESC != value))
			{
				this._COSTCENTERDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANYLOCATION", DbType="VarChar(25)")]
	public string COMPANYLOCATION
	{
		get
		{
			return this._COMPANYLOCATION;
		}
		set
		{
			if ((this._COMPANYLOCATION != value))
			{
				this._COMPANYLOCATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANYJOINDATE", DbType="VarChar(10)")]
	public string COMPANYJOINDATE
	{
		get
		{
			return this._COMPANYJOINDATE;
		}
		set
		{
			if ((this._COMPANYJOINDATE != value))
			{
				this._COMPANYJOINDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAININGDATE", DbType="VarChar(10)")]
	public string TRAININGDATE
	{
		get
		{
			return this._TRAININGDATE;
		}
		set
		{
			if ((this._TRAININGDATE != value))
			{
				this._TRAININGDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROBATIONDATE", DbType="VarChar(10)")]
	public string PROBATIONDATE
	{
		get
		{
			return this._PROBATIONDATE;
		}
		set
		{
			if ((this._PROBATIONDATE != value))
			{
				this._PROBATIONDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTDATE", DbType="VarChar(10)")]
	public string CONTRACTDATE
	{
		get
		{
			return this._CONTRACTDATE;
		}
		set
		{
			if ((this._CONTRACTDATE != value))
			{
				this._CONTRACTDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMATIONDATE", DbType="VarChar(10)")]
	public string CONFIRMATIONDATE
	{
		get
		{
			return this._CONFIRMATIONDATE;
		}
		set
		{
			if ((this._CONFIRMATIONDATE != value))
			{
				this._CONFIRMATIONDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(4)")]
	public string LOCATION
	{
		get
		{
			return this._LOCATION;
		}
		set
		{
			if ((this._LOCATION != value))
			{
				this._LOCATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATIONDESC", DbType="VarChar(30)")]
	public string LOCATIONDESC
	{
		get
		{
			return this._LOCATIONDESC;
		}
		set
		{
			if ((this._LOCATIONDESC != value))
			{
				this._LOCATIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPGROUP", DbType="VarChar(1)")]
	public string EMPGROUP
	{
		get
		{
			return this._EMPGROUP;
		}
		set
		{
			if ((this._EMPGROUP != value))
			{
				this._EMPGROUP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPDESC", DbType="VarChar(20)")]
	public string GROUPDESC
	{
		get
		{
			return this._GROUPDESC;
		}
		set
		{
			if ((this._GROUPDESC != value))
			{
				this._GROUPDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATION", DbType="VarChar(2)")]
	public string DESIGNATION
	{
		get
		{
			return this._DESIGNATION;
		}
		set
		{
			if ((this._DESIGNATION != value))
			{
				this._DESIGNATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATIONDESC", DbType="VarChar(20)")]
	public string DESIGNATIONDESC
	{
		get
		{
			return this._DESIGNATIONDESC;
		}
		set
		{
			if ((this._DESIGNATIONDESC != value))
			{
				this._DESIGNATIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="VarChar(4)")]
	public string GRADE
	{
		get
		{
			return this._GRADE;
		}
		set
		{
			if ((this._GRADE != value))
			{
				this._GRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSAREA", DbType="VarChar(4)")]
	public string BUSAREA
	{
		get
		{
			return this._BUSAREA;
		}
		set
		{
			if ((this._BUSAREA != value))
			{
				this._BUSAREA = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSAREADESC", DbType="VarChar(30)")]
	public string BUSAREADESC
	{
		get
		{
			return this._BUSAREADESC;
		}
		set
		{
			if ((this._BUSAREADESC != value))
			{
				this._BUSAREADESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(4)")]
	public string DEPARTMENT
	{
		get
		{
			return this._DEPARTMENT;
		}
		set
		{
			if ((this._DEPARTMENT != value))
			{
				this._DEPARTMENT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENTDESC", DbType="VarChar(20)")]
	public string DEPARTMENTDESC
	{
		get
		{
			return this._DEPARTMENTDESC;
		}
		set
		{
			if ((this._DEPARTMENTDESC != value))
			{
				this._DEPARTMENTDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHID", DbType="VarChar(5)")]
	public string BRANCHID
	{
		get
		{
			return this._BRANCHID;
		}
		set
		{
			if ((this._BRANCHID != value))
			{
				this._BRANCHID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHIDDESC", DbType="VarChar(40)")]
	public string BRANCHIDDESC
	{
		get
		{
			return this._BRANCHIDDESC;
		}
		set
		{
			if ((this._BRANCHIDDESC != value))
			{
				this._BRANCHIDDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLL", DbType="VarChar(2)")]
	public string PAYROLL
	{
		get
		{
			return this._PAYROLL;
		}
		set
		{
			if ((this._PAYROLL != value))
			{
				this._PAYROLL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLLDESC", DbType="VarChar(40)")]
	public string PAYROLLDESC
	{
		get
		{
			return this._PAYROLLDESC;
		}
		set
		{
			if ((this._PAYROLLDESC != value))
			{
				this._PAYROLLDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="VarChar(8)")]
	public string ROLE
	{
		get
		{
			return this._ROLE;
		}
		set
		{
			if ((this._ROLE != value))
			{
				this._ROLE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLEDESC", DbType="VarChar(25)")]
	public string ROLEDESC
	{
		get
		{
			return this._ROLEDESC;
		}
		set
		{
			if ((this._ROLEDESC != value))
			{
				this._ROLEDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLANS", DbType="VarChar(8)")]
	public string PLANS
	{
		get
		{
			return this._PLANS;
		}
		set
		{
			if ((this._PLANS != value))
			{
				this._PLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODPLANS", DbType="VarChar(45)")]
	public string HODPLANS
	{
		get
		{
			return this._HODPLANS;
		}
		set
		{
			if ((this._HODPLANS != value))
			{
				this._HODPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODEMPID", DbType="VarChar(8)")]
	public string HODEMPID
	{
		get
		{
			return this._HODEMPID;
		}
		set
		{
			if ((this._HODEMPID != value))
			{
				this._HODEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODFULLNAME", DbType="VarChar(40)")]
	public string HODFULLNAME
	{
		get
		{
			return this._HODFULLNAME;
		}
		set
		{
			if ((this._HODFULLNAME != value))
			{
				this._HODFULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODEMAILID", DbType="VarChar(100)")]
	public string HODEMAILID
	{
		get
		{
			return this._HODEMAILID;
		}
		set
		{
			if ((this._HODEMAILID != value))
			{
				this._HODEMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODDESG", DbType="VarChar(2)")]
	public string HODDESG
	{
		get
		{
			return this._HODDESG;
		}
		set
		{
			if ((this._HODDESG != value))
			{
				this._HODDESG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODDESGDESC", DbType="VarChar(20)")]
	public string HODDESGDESC
	{
		get
		{
			return this._HODDESGDESC;
		}
		set
		{
			if ((this._HODDESGDESC != value))
			{
				this._HODDESGDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODGRADE", DbType="VarChar(4)")]
	public string HODGRADE
	{
		get
		{
			return this._HODGRADE;
		}
		set
		{
			if ((this._HODGRADE != value))
			{
				this._HODGRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPREPORTTOPLANS", DbType="VarChar(45)")]
	public string EMPREPORTTOPLANS
	{
		get
		{
			return this._EMPREPORTTOPLANS;
		}
		set
		{
			if ((this._EMPREPORTTOPLANS != value))
			{
				this._EMPREPORTTOPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOEMPID", DbType="VarChar(8)")]
	public string REPORTTOEMPID
	{
		get
		{
			return this._REPORTTOEMPID;
		}
		set
		{
			if ((this._REPORTTOEMPID != value))
			{
				this._REPORTTOEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOFULLNAME", DbType="VarChar(40)")]
	public string REPORTTOFULLNAME
	{
		get
		{
			return this._REPORTTOFULLNAME;
		}
		set
		{
			if ((this._REPORTTOFULLNAME != value))
			{
				this._REPORTTOFULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOEMAILID", DbType="VarChar(100)")]
	public string REPORTTOEMAILID
	{
		get
		{
			return this._REPORTTOEMAILID;
		}
		set
		{
			if ((this._REPORTTOEMAILID != value))
			{
				this._REPORTTOEMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTODESG", DbType="VarChar(2)")]
	public string REPORTTODESG
	{
		get
		{
			return this._REPORTTODESG;
		}
		set
		{
			if ((this._REPORTTODESG != value))
			{
				this._REPORTTODESG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTODESGDESC", DbType="VarChar(20)")]
	public string REPORTTODESGDESC
	{
		get
		{
			return this._REPORTTODESGDESC;
		}
		set
		{
			if ((this._REPORTTODESGDESC != value))
			{
				this._REPORTTODESGDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOGRADE", DbType="VarChar(4)")]
	public string REPORTTOGRADE
	{
		get
		{
			return this._REPORTTOGRADE;
		}
		set
		{
			if ((this._REPORTTOGRADE != value))
			{
				this._REPORTTOGRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(40)")]
	public string FULLNAME
	{
		get
		{
			return this._FULLNAME;
		}
		set
		{
			if ((this._FULLNAME != value))
			{
				this._FULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="VarChar(40)")]
	public string FNAME
	{
		get
		{
			return this._FNAME;
		}
		set
		{
			if ((this._FNAME != value))
			{
				this._FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNAME", DbType="VarChar(40)")]
	public string MNAME
	{
		get
		{
			return this._MNAME;
		}
		set
		{
			if ((this._MNAME != value))
			{
				this._MNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNAME", DbType="VarChar(40)")]
	public string LNAME
	{
		get
		{
			return this._LNAME;
		}
		set
		{
			if ((this._LNAME != value))
			{
				this._LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(10)")]
	public string DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(3)")]
	public string REGION
	{
		get
		{
			return this._REGION;
		}
		set
		{
			if ((this._REGION != value))
			{
				this._REGION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHPLACE", DbType="VarChar(25)")]
	public string BIRTHPLACE
	{
		get
		{
			return this._BIRTHPLACE;
		}
		set
		{
			if ((this._BIRTHPLACE != value))
			{
				this._BIRTHPLACE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHCOUNTRY", DbType="VarChar(3)")]
	public string BIRTHCOUNTRY
	{
		get
		{
			return this._BIRTHCOUNTRY;
		}
		set
		{
			if ((this._BIRTHCOUNTRY != value))
			{
				this._BIRTHCOUNTRY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHCOUNTRYDESC", DbType="VarChar(15)")]
	public string BIRTHCOUNTRYDESC
	{
		get
		{
			return this._BIRTHCOUNTRYDESC;
		}
		set
		{
			if ((this._BIRTHCOUNTRYDESC != value))
			{
				this._BIRTHCOUNTRYDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIONDESC", DbType="VarChar(20)")]
	public string REGIONDESC
	{
		get
		{
			return this._REGIONDESC;
		}
		set
		{
			if ((this._REGIONDESC != value))
			{
				this._REGIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILENO", DbType="VarChar(12)")]
	public string MOBILENO
	{
		get
		{
			return this._MOBILENO;
		}
		set
		{
			if ((this._MOBILENO != value))
			{
				this._MOBILENO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDLINE", DbType="VarChar(12)")]
	public string LANDLINE
	{
		get
		{
			return this._LANDLINE;
		}
		set
		{
			if ((this._LANDLINE != value))
			{
				this._LANDLINE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILID", DbType="VarChar(100)")]
	public string EMAILID
	{
		get
		{
			return this._EMAILID;
		}
		set
		{
			if ((this._EMAILID != value))
			{
				this._EMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCOMPLETION", DbType="VarChar(10)")]
	public string EDUCOMPLETION
	{
		get
		{
			return this._EDUCOMPLETION;
		}
		set
		{
			if ((this._EDUCOMPLETION != value))
			{
				this._EDUCOMPLETION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTITUTE", DbType="VarChar(80)")]
	public string INSTITUTE
	{
		get
		{
			return this._INSTITUTE;
		}
		set
		{
			if ((this._INSTITUTE != value))
			{
				this._INSTITUTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CERTIFICATION", DbType="VarChar(2)")]
	public string CERTIFICATION
	{
		get
		{
			return this._CERTIFICATION;
		}
		set
		{
			if ((this._CERTIFICATION != value))
			{
				this._CERTIFICATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCATION", DbType="VarChar(2)")]
	public string EDUCATION
	{
		get
		{
			return this._EDUCATION;
		}
		set
		{
			if ((this._EDUCATION != value))
			{
				this._EDUCATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCATIONDESC", DbType="VarChar(40)")]
	public string EDUCATIONDESC
	{
		get
		{
			return this._EDUCATIONDESC;
		}
		set
		{
			if ((this._EDUCATIONDESC != value))
			{
				this._EDUCATIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCLASS", DbType="VarChar(2)")]
	public string EDUCLASS
	{
		get
		{
			return this._EDUCLASS;
		}
		set
		{
			if ((this._EDUCLASS != value))
			{
				this._EDUCLASS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERCENTAGE", DbType="VarChar(9)")]
	public string PERCENTAGE
	{
		get
		{
			return this._PERCENTAGE;
		}
		set
		{
			if ((this._PERCENTAGE != value))
			{
				this._PERCENTAGE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUGRADE", DbType="VarChar(8)")]
	public string EDUGRADE
	{
		get
		{
			return this._EDUGRADE;
		}
		set
		{
			if ((this._EDUGRADE != value))
			{
				this._EDUGRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PANNO", DbType="VarChar(20)")]
	public string PANNO
	{
		get
		{
			return this._PANNO;
		}
		set
		{
			if ((this._PANNO != value))
			{
				this._PANNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSPORT", DbType="VarChar(20)")]
	public string PASSPORT
	{
		get
		{
			return this._PASSPORT;
		}
		set
		{
			if ((this._PASSPORT != value))
			{
				this._PASSPORT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSPORTEXPDATE", DbType="VarChar(10)")]
	public string PASSPORTEXPDATE
	{
		get
		{
			return this._PASSPORTEXPDATE;
		}
		set
		{
			if ((this._PASSPORTEXPDATE != value))
			{
				this._PASSPORTEXPDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSPORTISSUING", DbType="VarChar(3)")]
	public string PASSPORTISSUING
	{
		get
		{
			return this._PASSPORTISSUING;
		}
		set
		{
			if ((this._PASSPORTISSUING != value))
			{
				this._PASSPORTISSUING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSPORTCOUNTRY", DbType="VarChar(15)")]
	public string PASSPORTCOUNTRY
	{
		get
		{
			return this._PASSPORTCOUNTRY;
		}
		set
		{
			if ((this._PASSPORTCOUNTRY != value))
			{
				this._PASSPORTCOUNTRY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREET", DbType="VarChar(60)")]
	public string STREET
	{
		get
		{
			return this._STREET;
		}
		set
		{
			if ((this._STREET != value))
			{
				this._STREET = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(40)")]
	public string CITY
	{
		get
		{
			return this._CITY;
		}
		set
		{
			if ((this._CITY != value))
			{
				this._CITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(40)")]
	public string DISTRICT
	{
		get
		{
			return this._DISTRICT;
		}
		set
		{
			if ((this._DISTRICT != value))
			{
				this._DISTRICT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="VarChar(10)")]
	public string POSTALCODE
	{
		get
		{
			return this._POSTALCODE;
		}
		set
		{
			if ((this._POSTALCODE != value))
			{
				this._POSTALCODE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOMECOUNTRY", DbType="VarChar(3)")]
	public string HOMECOUNTRY
	{
		get
		{
			return this._HOMECOUNTRY;
		}
		set
		{
			if ((this._HOMECOUNTRY != value))
			{
				this._HOMECOUNTRY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOMETELEPHONE", DbType="VarChar(14)")]
	public string HOMETELEPHONE
	{
		get
		{
			return this._HOMETELEPHONE;
		}
		set
		{
			if ((this._HOMETELEPHONE != value))
			{
				this._HOMETELEPHONE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREETLINE", DbType="VarChar(40)")]
	public string STREETLINE
	{
		get
		{
			return this._STREETLINE;
		}
		set
		{
			if ((this._STREETLINE != value))
			{
				this._STREETLINE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOMEREGION", DbType="VarChar(3)")]
	public string HOMEREGION
	{
		get
		{
			return this._HOMEREGION;
		}
		set
		{
			if ((this._HOMEREGION != value))
			{
				this._HOMEREGION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOMEREGIONDESC", DbType="VarChar(20)")]
	public string HOMEREGIONDESC
	{
		get
		{
			return this._HOMEREGIONDESC;
		}
		set
		{
			if ((this._HOMEREGIONDESC != value))
			{
				this._HOMEREGIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOMECOUNTRYDESC", DbType="VarChar(15)")]
	public string HOMECOUNTRYDESC
	{
		get
		{
			return this._HOMECOUNTRYDESC;
		}
		set
		{
			if ((this._HOMECOUNTRYDESC != value))
			{
				this._HOMECOUNTRYDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRYINTOGROUP", DbType="DateTime")]
	public System.Nullable<System.DateTime> ENTRYINTOGROUP
	{
		get
		{
			return this._ENTRYINTOGROUP;
		}
		set
		{
			if ((this._ENTRYINTOGROUP != value))
			{
				this._ENTRYINTOGROUP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORPORATION", DbType="VarChar(5)")]
	public string CORPORATION
	{
		get
		{
			return this._CORPORATION;
		}
		set
		{
			if ((this._CORPORATION != value))
			{
				this._CORPORATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORPORATIONDESC", DbType="VarChar(8)")]
	public string CORPORATIONDESC
	{
		get
		{
			return this._CORPORATIONDESC;
		}
		set
		{
			if ((this._CORPORATIONDESC != value))
			{
				this._CORPORATIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTHER_FNAME", DbType="VarChar(25)")]
	public string MOTHER_FNAME
	{
		get
		{
			return this._MOTHER_FNAME;
		}
		set
		{
			if ((this._MOTHER_FNAME != value))
			{
				this._MOTHER_FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTHER_LNAME", DbType="VarChar(40)")]
	public string MOTHER_LNAME
	{
		get
		{
			return this._MOTHER_LNAME;
		}
		set
		{
			if ((this._MOTHER_LNAME != value))
			{
				this._MOTHER_LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTHERDOB", DbType="VarChar(10)")]
	public string MOTHERDOB
	{
		get
		{
			return this._MOTHERDOB;
		}
		set
		{
			if ((this._MOTHERDOB != value))
			{
				this._MOTHERDOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER_FNAME", DbType="VarChar(25)")]
	public string FATHER_FNAME
	{
		get
		{
			return this._FATHER_FNAME;
		}
		set
		{
			if ((this._FATHER_FNAME != value))
			{
				this._FATHER_FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER_LNAME", DbType="VarChar(40)")]
	public string FATHER_LNAME
	{
		get
		{
			return this._FATHER_LNAME;
		}
		set
		{
			if ((this._FATHER_LNAME != value))
			{
				this._FATHER_LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHERDOB", DbType="VarChar(10)")]
	public string FATHERDOB
	{
		get
		{
			return this._FATHERDOB;
		}
		set
		{
			if ((this._FATHERDOB != value))
			{
				this._FATHERDOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIFE_FNAME", DbType="VarChar(25)")]
	public string WIFE_FNAME
	{
		get
		{
			return this._WIFE_FNAME;
		}
		set
		{
			if ((this._WIFE_FNAME != value))
			{
				this._WIFE_FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIFE_LNAME", DbType="VarChar(40)")]
	public string WIFE_LNAME
	{
		get
		{
			return this._WIFE_LNAME;
		}
		set
		{
			if ((this._WIFE_LNAME != value))
			{
				this._WIFE_LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIFEDOB", DbType="VarChar(10)")]
	public string WIFEDOB
	{
		get
		{
			return this._WIFEDOB;
		}
		set
		{
			if ((this._WIFEDOB != value))
			{
				this._WIFEDOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTPROMOTION", DbType="DateTime")]
	public System.Nullable<System.DateTime> LASTPROMOTION
	{
		get
		{
			return this._LASTPROMOTION;
		}
		set
		{
			if ((this._LASTPROMOTION != value))
			{
				this._LASTPROMOTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTCOMPANY", DbType="VarChar(20)")]
	public string LASTCOMPANY
	{
		get
		{
			return this._LASTCOMPANY;
		}
		set
		{
			if ((this._LASTCOMPANY != value))
			{
				this._LASTCOMPANY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTCOMPANYJOIN", DbType="DateTime")]
	public System.Nullable<System.DateTime> LASTCOMPANYJOIN
	{
		get
		{
			return this._LASTCOMPANYJOIN;
		}
		set
		{
			if ((this._LASTCOMPANYJOIN != value))
			{
				this._LASTCOMPANYJOIN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTCOMPANYLEAVE", DbType="DateTime")]
	public System.Nullable<System.DateTime> LASTCOMPANYLEAVE
	{
		get
		{
			return this._LASTCOMPANYLEAVE;
		}
		set
		{
			if ((this._LASTCOMPANYLEAVE != value))
			{
				this._LASTCOMPANYLEAVE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREEMPNUMBER", DbType="VarChar(8)")]
	public string PREEMPNUMBER
	{
		get
		{
			return this._PREEMPNUMBER;
		}
		set
		{
			if ((this._PREEMPNUMBER != value))
			{
				this._PREEMPNUMBER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVEENTITLE", DbType="Decimal(10,5)")]
	public System.Nullable<decimal> LEAVEENTITLE
	{
		get
		{
			return this._LEAVEENTITLE;
		}
		set
		{
			if ((this._LEAVEENTITLE != value))
			{
				this._LEAVEENTITLE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVEREST", DbType="Decimal(10,5)")]
	public System.Nullable<decimal> LEAVEREST
	{
		get
		{
			return this._LEAVEREST;
		}
		set
		{
			if ((this._LEAVEREST != value))
			{
				this._LEAVEREST = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVEDEDUCT", DbType="Decimal(10,5)")]
	public System.Nullable<decimal> LEAVEDEDUCT
	{
		get
		{
			return this._LEAVEDEDUCT;
		}
		set
		{
			if ((this._LEAVEDEDUCT != value))
			{
				this._LEAVEDEDUCT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOODGROUPID", DbType="VarChar(2)")]
	public string BLOODGROUPID
	{
		get
		{
			return this._BLOODGROUPID;
		}
		set
		{
			if ((this._BLOODGROUPID != value))
			{
				this._BLOODGROUPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOODGROUPDESC", DbType="VarChar(25)")]
	public string BLOODGROUPDESC
	{
		get
		{
			return this._BLOODGROUPDESC;
		}
		set
		{
			if ((this._BLOODGROUPDESC != value))
			{
				this._BLOODGROUPDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARRITALSTATUSID", DbType="VarChar(1)")]
	public string MARRITALSTATUSID
	{
		get
		{
			return this._MARRITALSTATUSID;
		}
		set
		{
			if ((this._MARRITALSTATUSID != value))
			{
				this._MARRITALSTATUSID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOOFCHILD", DbType="Decimal(3,0)")]
	public System.Nullable<decimal> NOOFCHILD
	{
		get
		{
			return this._NOOFCHILD;
		}
		set
		{
			if ((this._NOOFCHILD != value))
			{
				this._NOOFCHILD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONALITY", DbType="VarChar(3)")]
	public string NATIONALITY
	{
		get
		{
			return this._NATIONALITY;
		}
		set
		{
			if ((this._NATIONALITY != value))
			{
				this._NATIONALITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONALITYDESC", DbType="VarChar(50)")]
	public string NATIONALITYDESC
	{
		get
		{
			return this._NATIONALITYDESC;
		}
		set
		{
			if ((this._NATIONALITYDESC != value))
			{
				this._NATIONALITYDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(1)")]
	public string GENDER
	{
		get
		{
			return this._GENDER;
		}
		set
		{
			if ((this._GENDER != value))
			{
				this._GENDER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDERDESC", DbType="VarChar(6)")]
	public string GENDERDESC
	{
		get
		{
			return this._GENDERDESC;
		}
		set
		{
			if ((this._GENDERDESC != value))
			{
				this._GENDERDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANNIVERSARYDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> ANNIVERSARYDATE
	{
		get
		{
			return this._ANNIVERSARYDATE;
		}
		set
		{
			if ((this._ANNIVERSARYDATE != value))
			{
				this._ANNIVERSARYDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGION", DbType="VarChar(2)")]
	public string RELIGION
	{
		get
		{
			return this._RELIGION;
		}
		set
		{
			if ((this._RELIGION != value))
			{
				this._RELIGION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGIONDESC", DbType="VarChar(25)")]
	public string RELIGIONDESC
	{
		get
		{
			return this._RELIGIONDESC;
		}
		set
		{
			if ((this._RELIGIONDESC != value))
			{
				this._RELIGIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETIREMENT", DbType="DateTime")]
	public System.Nullable<System.DateTime> RETIREMENT
	{
		get
		{
			return this._RETIREMENT;
		}
		set
		{
			if ((this._RETIREMENT != value))
			{
				this._RETIREMENT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKACCOUNT", DbType="VarChar(18)")]
	public string BANKACCOUNT
	{
		get
		{
			return this._BANKACCOUNT;
		}
		set
		{
			if ((this._BANKACCOUNT != value))
			{
				this._BANKACCOUNT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNAME", DbType="VarChar(15)")]
	public string BANKNAME
	{
		get
		{
			return this._BANKNAME;
		}
		set
		{
			if ((this._BANKNAME != value))
			{
				this._BANKNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREHODEMPID", DbType="VarChar(8)")]
	public string PREHODEMPID
	{
		get
		{
			return this._PREHODEMPID;
		}
		set
		{
			if ((this._PREHODEMPID != value))
			{
				this._PREHODEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREHODFULLNAME", DbType="VarChar(40)")]
	public string PREHODFULLNAME
	{
		get
		{
			return this._PREHODFULLNAME;
		}
		set
		{
			if ((this._PREHODFULLNAME != value))
			{
				this._PREHODFULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREHODEMAILID", DbType="VarChar(100)")]
	public string PREHODEMAILID
	{
		get
		{
			return this._PREHODEMAILID;
		}
		set
		{
			if ((this._PREHODEMAILID != value))
			{
				this._PREHODEMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOEMPID", DbType="VarChar(8)")]
	public string PREREPORTTOEMPID
	{
		get
		{
			return this._PREREPORTTOEMPID;
		}
		set
		{
			if ((this._PREREPORTTOEMPID != value))
			{
				this._PREREPORTTOEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOPLANS", DbType="VarChar(45)")]
	public string PREREPORTTOPLANS
	{
		get
		{
			return this._PREREPORTTOPLANS;
		}
		set
		{
			if ((this._PREREPORTTOPLANS != value))
			{
				this._PREREPORTTOPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTLASTCHANGE", DbType="VarChar(10)")]
	public string DEPTLASTCHANGE
	{
		get
		{
			return this._DEPTLASTCHANGE;
		}
		set
		{
			if ((this._DEPTLASTCHANGE != value))
			{
				this._DEPTLASTCHANGE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOCOMP", DbType="VarChar(4)")]
	public string PREREPORTTOCOMP
	{
		get
		{
			return this._PREREPORTTOCOMP;
		}
		set
		{
			if ((this._PREREPORTTOCOMP != value))
			{
				this._PREREPORTTOCOMP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOLOC", DbType="VarChar(4)")]
	public string PREREPORTTOLOC
	{
		get
		{
			return this._PREREPORTTOLOC;
		}
		set
		{
			if ((this._PREREPORTTOLOC != value))
			{
				this._PREREPORTTOLOC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTODEPT", DbType="VarChar(4)")]
	public string PREREPORTTODEPT
	{
		get
		{
			return this._PREREPORTTODEPT;
		}
		set
		{
			if ((this._PREREPORTTODEPT != value))
			{
				this._PREREPORTTODEPT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREREPORTTOROLE", DbType="VarChar(8)")]
	public string PREREPORTTOROLE
	{
		get
		{
			return this._PREREPORTTOROLE;
		}
		set
		{
			if ((this._PREREPORTTOROLE != value))
			{
				this._PREREPORTTOROLE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSSTREET", DbType="VarChar(60)")]
	public string TSSTREET
	{
		get
		{
			return this._TSSTREET;
		}
		set
		{
			if ((this._TSSTREET != value))
			{
				this._TSSTREET = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSCITY", DbType="VarChar(40)")]
	public string TSCITY
	{
		get
		{
			return this._TSCITY;
		}
		set
		{
			if ((this._TSCITY != value))
			{
				this._TSCITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSDISTRICT", DbType="VarChar(40)")]
	public string TSDISTRICT
	{
		get
		{
			return this._TSDISTRICT;
		}
		set
		{
			if ((this._TSDISTRICT != value))
			{
				this._TSDISTRICT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSPOSTALCODE", DbType="VarChar(10)")]
	public string TSPOSTALCODE
	{
		get
		{
			return this._TSPOSTALCODE;
		}
		set
		{
			if ((this._TSPOSTALCODE != value))
			{
				this._TSPOSTALCODE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSHOMECOUNTRY", DbType="VarChar(3)")]
	public string TSHOMECOUNTRY
	{
		get
		{
			return this._TSHOMECOUNTRY;
		}
		set
		{
			if ((this._TSHOMECOUNTRY != value))
			{
				this._TSHOMECOUNTRY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSHOMETELEPHONE", DbType="VarChar(14)")]
	public string TSHOMETELEPHONE
	{
		get
		{
			return this._TSHOMETELEPHONE;
		}
		set
		{
			if ((this._TSHOMETELEPHONE != value))
			{
				this._TSHOMETELEPHONE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSSTREETLINE", DbType="VarChar(40)")]
	public string TSSTREETLINE
	{
		get
		{
			return this._TSSTREETLINE;
		}
		set
		{
			if ((this._TSSTREETLINE != value))
			{
				this._TSSTREETLINE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSHOMEREGION", DbType="VarChar(3)")]
	public string TSHOMEREGION
	{
		get
		{
			return this._TSHOMEREGION;
		}
		set
		{
			if ((this._TSHOMEREGION != value))
			{
				this._TSHOMEREGION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSHOMEREGIONDESC", DbType="VarChar(20)")]
	public string TSHOMEREGIONDESC
	{
		get
		{
			return this._TSHOMEREGIONDESC;
		}
		set
		{
			if ((this._TSHOMEREGIONDESC != value))
			{
				this._TSHOMEREGIONDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOINEDAS", DbType="VarChar(2)")]
	public string JOINEDAS
	{
		get
		{
			return this._JOINEDAS;
		}
		set
		{
			if ((this._JOINEDAS != value))
			{
				this._JOINEDAS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOINEDASDESC", DbType="VarChar(30)")]
	public string JOINEDASDESC
	{
		get
		{
			return this._JOINEDASDESC;
		}
		set
		{
			if ((this._JOINEDASDESC != value))
			{
				this._JOINEDASDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVECOP", DbType="VarChar(17)")]
	public string LEAVECOP
	{
		get
		{
			return this._LEAVECOP;
		}
		set
		{
			if ((this._LEAVECOP != value))
			{
				this._LEAVECOP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVECOT", DbType="VarChar(17)")]
	public string LEAVECOT
	{
		get
		{
			return this._LEAVECOT;
		}
		set
		{
			if ((this._LEAVECOT != value))
			{
				this._LEAVECOT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPID6", DbType="VarChar(6)")]
	public string EMPID6
	{
		get
		{
			return this._EMPID6;
		}
		set
		{
			if ((this._EMPID6 != value))
			{
				this._EMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HODEMPID6", DbType="VarChar(6)")]
	public string HODEMPID6
	{
		get
		{
			return this._HODEMPID6;
		}
		set
		{
			if ((this._HODEMPID6 != value))
			{
				this._HODEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOEMPID6", DbType="VarChar(6)")]
	public string REPORTTOEMPID6
	{
		get
		{
			return this._REPORTTOEMPID6;
		}
		set
		{
			if ((this._REPORTTOEMPID6 != value))
			{
				this._REPORTTOEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREHODEMPID6", DbType="VarChar(6)")]
	public string PREHODEMPID6
	{
		get
		{
			return this._PREHODEMPID6;
		}
		set
		{
			if ((this._PREHODEMPID6 != value))
			{
				this._PREHODEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAR", DbType="VarChar(32)")]
	public string STAR
	{
		get
		{
			return this._STAR;
		}
		set
		{
			if ((this._STAR != value))
			{
				this._STAR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTOPLANS", DbType="VarChar(8)")]
	public string REPORTTOPLANS
	{
		get
		{
			return this._REPORTTOPLANS;
		}
		set
		{
			if ((this._REPORTTOPLANS != value))
			{
				this._REPORTTOPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVEMPID", DbType="VarChar(8)")]
	public string REVEMPID
	{
		get
		{
			return this._REVEMPID;
		}
		set
		{
			if ((this._REVEMPID != value))
			{
				this._REVEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVFULLNAME", DbType="VarChar(40)")]
	public string REVFULLNAME
	{
		get
		{
			return this._REVFULLNAME;
		}
		set
		{
			if ((this._REVFULLNAME != value))
			{
				this._REVFULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVEMAILID", DbType="VarChar(100)")]
	public string REVEMAILID
	{
		get
		{
			return this._REVEMAILID;
		}
		set
		{
			if ((this._REVEMAILID != value))
			{
				this._REVEMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVDESG", DbType="VarChar(2)")]
	public string REVDESG
	{
		get
		{
			return this._REVDESG;
		}
		set
		{
			if ((this._REVDESG != value))
			{
				this._REVDESG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVDESGDESC", DbType="VarChar(20)")]
	public string REVDESGDESC
	{
		get
		{
			return this._REVDESGDESC;
		}
		set
		{
			if ((this._REVDESGDESC != value))
			{
				this._REVDESGDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVGRADE", DbType="VarChar(4)")]
	public string REVGRADE
	{
		get
		{
			return this._REVGRADE;
		}
		set
		{
			if ((this._REVGRADE != value))
			{
				this._REVGRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVEMPID6", DbType="VarChar(6)")]
	public string REVEMPID6
	{
		get
		{
			return this._REVEMPID6;
		}
		set
		{
			if ((this._REVEMPID6 != value))
			{
				this._REVEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATEMPID", DbType="VarChar(8)")]
	public string MATEMPID
	{
		get
		{
			return this._MATEMPID;
		}
		set
		{
			if ((this._MATEMPID != value))
			{
				this._MATEMPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATFULLNAME", DbType="VarChar(40)")]
	public string MATFULLNAME
	{
		get
		{
			return this._MATFULLNAME;
		}
		set
		{
			if ((this._MATFULLNAME != value))
			{
				this._MATFULLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATEMAILID", DbType="VarChar(100)")]
	public string MATEMAILID
	{
		get
		{
			return this._MATEMAILID;
		}
		set
		{
			if ((this._MATEMAILID != value))
			{
				this._MATEMAILID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATDESG", DbType="VarChar(2)")]
	public string MATDESG
	{
		get
		{
			return this._MATDESG;
		}
		set
		{
			if ((this._MATDESG != value))
			{
				this._MATDESG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATDESGDESC", DbType="VarChar(20)")]
	public string MATDESGDESC
	{
		get
		{
			return this._MATDESGDESC;
		}
		set
		{
			if ((this._MATDESGDESC != value))
			{
				this._MATDESGDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATGRADE", DbType="VarChar(4)")]
	public string MATGRADE
	{
		get
		{
			return this._MATGRADE;
		}
		set
		{
			if ((this._MATGRADE != value))
			{
				this._MATGRADE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATEMPID6", DbType="VarChar(6)")]
	public string MATEMPID6
	{
		get
		{
			return this._MATEMPID6;
		}
		set
		{
			if ((this._MATEMPID6 != value))
			{
				this._MATEMPID6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATPLANS", DbType="VarChar(45)")]
	public string MATPLANS
	{
		get
		{
			return this._MATPLANS;
		}
		set
		{
			if ((this._MATPLANS != value))
			{
				this._MATPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAVEMATRIXMGR", DbType="VarChar(1)")]
	public string HAVEMATRIXMGR
	{
		get
		{
			return this._HAVEMATRIXMGR;
		}
		set
		{
			if ((this._HAVEMATRIXMGR != value))
			{
				this._HAVEMATRIXMGR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVPLANS", DbType="VarChar(45)")]
	public string REVPLANS
	{
		get
		{
			return this._REVPLANS;
		}
		set
		{
			if ((this._REVPLANS != value))
			{
				this._REVPLANS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESSAPPID", DbType="VarChar(8)")]
	public string ESSAPPID
	{
		get
		{
			return this._ESSAPPID;
		}
		set
		{
			if ((this._ESSAPPID != value))
			{
				this._ESSAPPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESSAPPNAME", DbType="VarChar(40)")]
	public string ESSAPPNAME
	{
		get
		{
			return this._ESSAPPNAME;
		}
		set
		{
			if ((this._ESSAPPNAME != value))
			{
				this._ESSAPPNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESSAPPINTA", DbType="VarChar(100)")]
	public string ESSAPPINTA
	{
		get
		{
			return this._ESSAPPINTA;
		}
		set
		{
			if ((this._ESSAPPINTA != value))
			{
				this._ESSAPPINTA = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_AGE", DbType="VarChar(2)")]
	public string EMP_AGE
	{
		get
		{
			return this._EMP_AGE;
		}
		set
		{
			if ((this._EMP_AGE != value))
			{
				this._EMP_AGE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_EXP", DbType="VarChar(50)")]
	public string EMP_EXP
	{
		get
		{
			return this._EMP_EXP;
		}
		set
		{
			if ((this._EMP_EXP != value))
			{
				this._EMP_EXP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_EXITDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> EMP_EXITDATE
	{
		get
		{
			return this._EMP_EXITDATE;
		}
		set
		{
			if ((this._EMP_EXITDATE != value))
			{
				this._EMP_EXITDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_BANKIFSC", DbType="VarChar(50)")]
	public string EMP_BANKIFSC
	{
		get
		{
			return this._EMP_BANKIFSC;
		}
		set
		{
			if ((this._EMP_BANKIFSC != value))
			{
				this._EMP_BANKIFSC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TSBLOCK", DbType="VarChar(50)")]
	public string EMP_TSBLOCK
	{
		get
		{
			return this._EMP_TSBLOCK;
		}
		set
		{
			if ((this._EMP_TSBLOCK != value))
			{
				this._EMP_TSBLOCK = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TSFLATNO", DbType="VarChar(50)")]
	public string EMP_TSFLATNO
	{
		get
		{
			return this._EMP_TSFLATNO;
		}
		set
		{
			if ((this._EMP_TSFLATNO != value))
			{
				this._EMP_TSFLATNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ACTIVE", DbType="VarChar(10)")]
	public string EMP_ACTIVE
	{
		get
		{
			return this._EMP_ACTIVE;
		}
		set
		{
			if ((this._EMP_ACTIVE != value))
			{
				this._EMP_ACTIVE = value;
			}
		}
	}
}
#pragma warning restore 1591
